server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./transaction;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      indent_output: true
  web:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

application:
  recommendations-db:
    url: jdbc:h2:file:./transaction

products:
  invest500:
    id: 147f6a0f-3b91-413b-ab99-87f081d60d5a
    name: Invest 500
    text: |
      Откройте свой путь к успеху с индивидуальным инвестиционным счетом (ИИС) от нашего банка!
      Воспользуйтесь налоговыми льготами и начните инвестировать с умом. Пополните счет до конца года и получите выгоду в виде вычета на взнос в следующем налоговом периоде.
      Не упустите возможность разнообразить свой портфель, снизить риски и следить за актуальными рыночными тенденциями. Откройте ИИС сегодня и станьте ближе к финансовой независимости!

  topSaving:
    id: 59efc529-2fff-41af-baff-90ccd7402925
    name: Top Saving
    text: |
      Откройте свою собственную «Копилку» с нашим банком! «Копилка» — это уникальный банковский инструмент, который поможет вам легко и удобно накапливать деньги на важные цели.
      Больше никаких забытых чеков и потерянных квитанций — всё под контролем!
      Преимущества «Копилки»:
      - Накопление средств на конкретные цели. Установите лимит и срок накопления, и банк будет автоматически переводить определенную сумму на ваш счет.
      - Прозрачность и контроль. Отслеживайте свои доходы и расходы, контролируйте процесс накопления и корректируйте стратегию при необходимости.
      - Безопасность и надежность. Ваши средства находятся под защитой банка, а доступ к ним возможен только через мобильное приложение или интернет-банкинг.

  simpleCredit:
    id: ab138afb-f3ba-4a93-b74f-0fcee86d447f
    name: Простой кредит
    text: |
      Откройте мир выгодных кредитов с нами! Мы предлагаем низкие процентные ставки, гибкие условия и индивидуальный подход к каждому клиенту.
      Почему выбирают нас:
      - Быстрое рассмотрение заявки. Мы ценим ваше время, поэтому процесс рассмотрения заявки занимает всего несколько часов.
      - Удобное оформление. Подать заявку на кредит можно онлайн на нашем сайте или в мобильном приложении.
      - Широкий выбор кредитных продуктов. Мы предлагаем кредиты на различные цели: покупку недвижимости, автомобиля, образование, лечение и многое другое.
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html